### ISSUE TITLE
`showtabline` is expecting a number

### ISSUE THREAD

**Issue by AlgusDark** [fasterius/simple-zoom.nvim#1]
Hi, thanks for this plugin. Is pretty cool and I'm liking it.

I noticed that, when I updated to latest neovim (0.10), I'm having this error where showtabline is expecting a number (according to neovim docs it should be from 0 to 2). [But in this line is setting a boolean](https://github.com/fasterius/simple-zoom.nvim/blob/33e42b142fc92d69223d1ee65024a410e3b87ffd/lua/simple-zoom.lua#L20). 

Is this a breaking change from Neovim? 🤔

**Comment by fasterius** [comment]
Hi! Glad that you like the plugin, and for the issue! Not sure why this started failing in 0.10, but it was a simple fix at least. Please update to the latest version and it should work now!
